name: C/C++ Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y nlohmann-json3-dev

      - name: Compilar
        run: |
          chmod +x compile.sh
          ./compile.sh

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          generate_release_notes: true
          files: callAI
